### ISSUE TITLE
Error in running tutorial2

### ISSUE THREAD

**Issue by qyz-thu** [informagi/REL#21]
I get following errors when running `tagger_ner = SequenceTagger.load("ner-fast")` in tutorial 2 on a server.
```
Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3d1878c50>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /alan-nlp/resources/models-v0.4/NER-conll03--h256-l1-b32-p3-0.5-%2Bglove%2Bnews-forward-fast%2Bnews-backward-fast-normal-locked0.5-word0.05--release_4/en-ner-fast-conll03-v0.4.pt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3d1878c50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xx/REL/rel_link.py", line 24, in <module>
    tagger_ner = SequenceTagger.load("ner-fast")
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/flair/nn.py", line 79, in load
    model_file = cls._fetch_model(str(model))
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 1013, in _fetch_model
    model_name = cached_path(model_map[model_name], cache_dir=cache_dir)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/flair/file_utils.py", line 88, in cached_path
    return get_from_cache(url_or_filename, dataset_cache)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/flair/file_utils.py", line 160, in get_from_cache
    response = requests.head(url, headers={"User-Agent": "Flair"})
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/xx/miniconda3/envs/rel/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /alan-nlp/resources/models-v0.4/NER-conll03--h256-l1-b32-p3-0.5-%2Bglove%2Bnews-forward-fast%2Bnews-backward-fast-normal-locked0.5-word0.05--release_4/en-ner-fast-conll03-v0.4.pt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3d1878c50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```
However, it doesn't seem that my server has any network problems. Is there anything I can do to fix this?

**Comment by arjenpdevries** [comment]
This seems to be a problem with access to AWS from Flair: see also https://github.com/flairNLP/flair/issues/938

I would not be surprised if it disappears automatically; please let us know if the problem persists.

**Comment by mickvanhulst** [comment]
Closing this error as this is most likely an error related to Flair. Please feel free to use our n-gram module as an alternative for your high Recall tasks.
