### ISSUE TITLE
Two issues for my project

### ISSUE THREAD

**Issue by DanBerrebbi** [informagi/REL#30]
Hello, I am currently doing a project and I'd like to use REL but I am facing some problems. 

1) The English preload models works well (wiki_2014, and 2019) but I need to evaluate the performance on the datasets by myself and I can't manage to do it even with the tutorials.

2) I also need to do it in French, so I've done the tutorial with the french wikipedia dump but I have problems with the anchor files wich are not the same format as in wiki_2014 for instance. 

I am not that good in this domain so I'll be glad if someone of your team could help me!

Thank you !

**Comment by mickvanhulst** [comment]
Hi Dan, 

To answer your questions:
1. If you simply input the text of these datasets and then evaluate the answers using your own metrics? No further preprocessing is required.
2. Did you extract the anchor files using [0]? Also remember that as you are using a different corpus (and language), you will have to retrain the Wikipedia embeddings which requires computational resources.

[0] https://github.com/informagi/REL/blob/master/tutorials/deploy_REL_new_Wiki/04_01_Extracting_a_new_Wikipedia_corpus.md

**Comment by DanBerrebbi** [comment]
thank you for your answer!

1) Ok I'm going to do this! 

2) I used 0 (exept that python told me that the file_size argument was not expected, so I removed it). Then  I had this folder : 
![image](https://user-images.githubusercontent.com/53098519/84767929-97ebe180-afd3-11ea-84e6-ad32ae986734.png) for the anchor file and not a unique .txt file as in wiki_2014.

**Comment by KDercksen** [comment]
Hi Dan,

> 2. I used 0 (exept that python told me that the file_size argument was not expected, so I removed it). Then  I had this folder :
>    ![image](https://user-images.githubusercontent.com/53098519/84767929-97ebe180-afd3-11ea-84e6-ad32ae986734.png) for the anchor file and not a unique .txt file as in wiki_2014.

The argument is `--bytes`, not `--file_size`; our mistake...

As long as all the individual files reside under the `anchor_files` directory, you should be okay. See also [here](https://github.com/informagi/REL/blob/master/REL/wikipedia_yago_freq.py#L242). You can probably get away by moving the anchor files into the correct place instead of rerunning the extraction script.

**Comment by DanBerrebbi** [comment]
Ok thank you for your answer, I am trying again!

**Comment by hasibi** [comment]
Hi Dan,

For (2), also note that we used multiple sources to build the P(e|m) index for English, one of the being Wikipedia. If you want to use only French Wikipedia to build the P(e|m) index for French, you may see some performance differences, especially for long-tail entities.

**Comment by DanBerrebbi** [comment]
Hi again, 
Thank you all for your help! 
1) and 2) are solved and I used a GPU of my school to make the training! (It went well so I have all the necessary folders now)

I am now at the step Storing Embeddings in DB and  I have some other issues. 
1) should the embedding_file = "./enwiki_w2v_model" be wikipedia2vec_trained  or wikipedia2vec_wv2vformat ?

2) When I use  wikipedia2vec_trained I get a utf-8 can't decode error due to the gensim.util.unicode function (and when I put the parameter error='ignore', then I have other problem later when  (line 56 in generic.py) there is int(x) for x in header.split(). 

3) When I use  wikipedia2vec_wv2vformat I have this error Traceback (most recent call last):
  File "store_DB_terminal.py", line 14, in <module>
    emb.load_word2emb(embedding_file, batch_size=5000, reset=True)
  File "/home/administrator/.local/lib/python3.7/site-packages/REL/db/generic.py", line 101, in load_word2emb
    self.avg_cnt["word"]["sum"] += vec
ValueError: operands could not be broadcast together with shapes (300,) (500,) (300,)  

(but I guess I have to use wikipedia2vec_trained so my main issue is 2) ) 

Thank you for your help!!

**Comment by KDercksen** [comment]
Hi Dan!

> 1. should the embedding_file = "./enwiki_w2v_model" be wikipedia2vec_trained  or wikipedia2vec_wv2vformat ?

You need the `wikipedia2vec_w2vformat` file. See also the discussion in #31 on replacing embeddings.

> 2. When I use  wikipedia2vec_trained I get a utf-8 can't decode error due to the gensim.util.unicode function (and when I put the parameter error='ignore', then I have other problem later when  (line 56 in generic.py) there is int(x) for x in header.split().

Probably caused by the above :)

> 3. When I use  wikipedia2vec_wv2vformat I have this error Traceback (most recent call last):
>    File "store_DB_terminal.py", line 14, in 
>    emb.load_word2emb(embedding_file, batch_size=5000, reset=True)
>    File "/home/administrator/.local/lib/python3.7/site-packages/REL/db/generic.py", line 101, in load_word2emb
>    self.avg_cnt["word"]["sum"] += vec
>    ValueError: operands could not be broadcast together with shapes (300,) (500,) (300,)

This is due to incorrect instantiation of the `GenericLookup` class; if you're using 500-dimensional embeddings, make sure to specify `d_emb=500` in the constructor arguments (see https://github.com/informagi/REL/blob/master/REL/db/generic.py#L13):

```python
emb = GenericLookup(db_name, save_dir=save_dir, table_name='embeddings', d_emb=500)
emb.load_word2emb(embedding_file, batch_size=5000, reset=True)
```

**Comment by DanBerrebbi** [comment]
Thanks a lot! This step is  running now! 

I have another question (sorry) : in the file  : https://github.com/informagi/REL/blob/master/REL/mention_detection.py#L35  (and previous lines), it seems that self.__sentences_doc is not declared before it is used, I tried to add self.__sentences_doc=sentence but I have an out of range index problem

**Comment by KDercksen** [comment]
Where/how are you running into that issue exactly? The `self.__sentences_doc` attribute should be populated automatically before use in either `format_spans` or `find_mentions`. Which functions are you calling?

**Comment by DanBerrebbi** [comment]
Actually I had this issue while running it on the wiki_14 to try. 

I tried (now that the previous step is ok) on my (french) corpus and I get this error 

![image](https://user-images.githubusercontent.com/53098519/84902621-562f6980-b0ad-11ea-882c-c79282a06898.png)

The script I am running is exactly  https://github.com/informagi/REL/blob/master/tutorials/deploy_REL_new_Wiki/04_03_generating_training_test_files.md

**Comment by KDercksen** [comment]
Did this stuff run correctly for you? https://github.com/informagi/REL/blob/master/tutorials/deploy_REL_new_Wiki/04_01_Extracting_a_new_Wikipedia_corpus.md#generate-pem-index

In particular, the `.store()` call should create the wiki table that is missing according to your error. This step will be slightly different for you as we use additional sources to create the p(e|m) index... I *think* if you comment [this](https://github.com/informagi/REL/blob/44cff62c0d497debbcc502a4bee0e09e87c162ad/REL/wikipedia_yago_freq.py#L51) line, and then run:

```python
wiki_yago_freq = WikipediaYagoFreq(base_url, wiki_version, wikipedia)
wiki_yago_freq.compute_wiki()
wiki_yago_freq.store()
```

it should get you (part of the way) there. It might take some more changes, feel free to dig around in the code a bit if it still does not work.

**Comment by DanBerrebbi** [comment]
When I do this the "Please take a break" last 0 second I don't know if it's fine 
![image](https://user-images.githubusercontent.com/53098519/84907815-f1c3d880-b0b3-11ea-95ac-829491913a64.png) 

and then I have the 
![image](https://user-images.githubusercontent.com/53098519/84907865-04d6a880-b0b4-11ea-9e1b-b861f8b1bb32.png)   issue I told you before for the 3rd tutorial -> 
![image](https://user-images.githubusercontent.com/53098519/84908146-6139c800-b0b4-11ea-8ea0-78f441cd36ee.png)

**Comment by KDercksen** [comment]
Right! Could you change [this](https://github.com/informagi/REL/blob/master/REL/generate_train_test.py#L44) line to say `self.__sentences_doc` instead of `self.sentences_doc`?

**Comment by DanBerrebbi** [comment]
I've done it but I still have the error : AttributeError: 'GenTrainingTest' object has no attribute '_MentionDetection__sentences_doc'

**Comment by KDercksen** [comment]
That's very strange. Can you post the output of `grep -rn --include \*.py "sentences_doc" /home/administrator/.local/lib/python3.7/site-packages/REL`

**Comment by DanBerrebbi** [comment]
![image](https://user-images.githubusercontent.com/53098519/84913168-84677600-b0ba-11ea-82e1-f2efaa376c69.png)

Yes this is weird because it seems to be the good spelling everywhere except in predict. 
(By the way thanks a lot for your help!)

**Comment by KDercksen** [comment]
Ok, this is slightly more complicated than I hoped... It is an inheritance issue that will take a while to fix neatly. In the meantime, you can copy the `_get_ctxt` method from `mention_detection.py` into the `GenTrainingTest` class, and add the appropriate imports.

We completely missed this bug, so it's good you encounter it (even though it must be quite annoying for you...).

**Comment by DanBerrebbi** [comment]
Ok it works with wiki_2014 (after adding get_ctxt). I hope it will be okay for the french corpus!
Thanks a lot!

**Comment by KDercksen** [comment]
Good to hear. Please keep us updated on any results on French tagging; we would love to hear how REL works out for your use-case! If you run into any further trouble, also let us know.

**Comment by DanBerrebbi** [comment]
yeah thank you 
I am in the last step 

I have 2 more questions : 
![image](https://user-images.githubusercontent.com/53098519/85001739-533b8400-b154-11ea-8f13-5bd94be7cb28.png)

1) I changed the d_emb from 300 to 500 already in generic.py but I don't find anywhere else that I could change it so I have this vector product issue

2) Why is the test-recall so low (is that because the test files are in English and my dump is in french ?)

**Comment by KDercksen** [comment]
> yeah thank you
> I am in the last step
> 
> I have 2 more questions :
> ![image](https://user-images.githubusercontent.com/53098519/85001739-533b8400-b154-11ea-8f13-5bd94be7cb28.png)
> 
> 1. I changed the d_emb from 300 to 500 already in generic.py but I don't find anywhere else that I could change it so I have this vector product issue

https://github.com/informagi/REL/blob/master/tutorials/deploy_REL_new_Wiki/04_04_training_your_own_ED_model.md make sure to add `"emb_dims": 500` to the config dictionary as well.

> 2. Why is the test-recall so low (is that because the test files are in English and my dump is in french ?)

Yes, evaluating your French model on an English dataset will result in low scores. You should evaluate French REL on a French entity linking or entity disambiguation dataset.

**Comment by DanBerrebbi** [comment]
Ok and what about the training (is that fine to train on AIDA ?)

for the size I now get this, I am not used to pytorch, how can I fix this ? 
![image](https://user-images.githubusercontent.com/53098519/85003955-381e4380-b157-11ea-8b91-1cb8fed91d3c.png)

**Comment by KDercksen** [comment]
Training on AIDA doesn't really make sense since it is English-only.

For your other question, I think we may have mixed up somewhere. Just to clarify, did you train 300-dimensional or 500-dimensional wikipedia2vec embeddings? You need 300-dimensional embeddings because the GloVe embeddings in `generic/common_drawl.db` are 300-dimensional as well... So this also means that everywhere I previously said 500 it should be 300 :cry: Apologies!

**Comment by mickvanhulst** [comment]
Closing due to inactivity
